version: '3'
services:
  redis:
    image: redis
    networks:
      booktype_net:
        aliases:
          - redis

  rabbit:
    image: rabbitmq
    networks:
      booktype_net:
        aliases:
          - rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  postgres:
    image: postgres
    networks:
      booktype_net:
        aliases:
          - db
          - postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=booktype
      - POSTGRES_PASSWORD=booktype
      - POSTGRES_DB=booktype

  nginx:
    build: nginx
    networks:
      booktype_net:
        aliases:
          - nginx
          - httpd

  uwsgi:
    build: uwsgi
    networks:
      booktype_net:
        aliases:
          - uwsgi

  booktype:
    build: booktype
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbit
      - postgres
      - nginx
      - uwsgi
    networks:
      - booktype_net
    volumes:
      - /srv/docker_volumes/booktype/data:/code/mybook/data:rw
      - /srv/docker_volumes/booktype/static:/code/mybook/static:rw
      - /srv/docker_volumes/booktype/logs:/code/mybook/logs:rw
      - /srv/docker_volumes/booktype/logs/supervisor:/var/log/supervisor:rw
      - /srv/docker_volumes/booktype/logs/nginx:/var/log/nginx:rw
volumes:
  pg_data: {}
  pg_backups: {}

networks:
    booktype_net:
